name: build and publish to test.pypi

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install wheel package
        run: pip install wheel

      - name: build wheel package
        run: python3 setup.py sdist bdist_wheel
      
      - name: archive artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: lib_RFM3270X
          path: dist/robotframework_mainframe3270_extended*.whl
  
      - name: upload to test.pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with: 
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
        
