# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install wheel package
        run: pip install wheel

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python setup.py bdist_wheel
      
      - name: archive artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: XM3270artifact.whl
          path: dist/robotframework_mainframe3270_extended*.whl
  
      - name: upload to test.pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with: 
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/
        
