name: build and release package to pypi

on : [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check python version
        run: python3 --version

      - name: Install required packages
        run: pip3 install robotframework==3.2.2 setuptools==50.3.2 six==1.15.0 wheel==0.35.1

      - name: build wheel package
        run: python3 setup.py bdist_wheel
      
      - name: upload to pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with: 
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          
