name: build and release package to pypi

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install wheel package
        run: pip install wheel

      - name: build wheel package
        run: python setup.py bdist_wheel
      
      - name: upload to pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with: 
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          